server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: g-picture-bankend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/g_picture?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345678
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0

# knife4j接口文档配置
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.gs.gpicturebackend.controller